### ISSUE TITLE
H2 Broombridge file seems incorrect

### ISSUE THREAD

**Issue by guenp** [microsoft/Quantum#506]
**Describe the bug**
@dgwvfxn pointed out that the Broombridge file for Hydrogen included in one of the Chemistry samples contains the incorrect SCF energy: [h2.yaml](https://github.com/microsoft/Quantum/blob/main/samples/chemistry/PythonIntegration/h2.yaml). He has generated a new file that should contain the correct values.

The values for the coulomb repulsion and SCF energy should be:
```
  coulomb_repulsion:
    value: 0.32584805972887831
    units: hartree
  scf_energy:
    value: -0.87499072
    units: hartree
```

Another error is the distance between H atoms: it is given in Bohr, not Angstrom.
